name: Push compiled jar to GitHub releases

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
    - name: Artifact
      uses: actions/upload-artifact@v1
      with:
        name: PlayerParticles-*.*-PGM.jar
        path: build/libs/PlayerParticles-*.*-PGM.jar
    - name: Move generated jar file
      run: mv build/libs/PlayerParticles-*.*-PGM.jar PlayerParticles-*.*-PGM.jar
    - name: Create Release
      id: create_release
      if: github.event_name != 'pull_request' && (github.ref == 'refs/heads/main')
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: PlayerParticles-PGM-${{github.sha}}
        release_name: Release ${{github.sha}}
        draft: false
        prerelease: false
    - name: Upload Release Asset
      id: upload-release-asset
      if: github.event_name != 'pull_request' && (github.ref == 'refs/heads/main')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./PlayerParticles-*.*-PGM.jar
        asset_name: PlayerParticles-*.*-PGM.jar
        asset_content_type: application/java-archive
